In [1]:
import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense

In [2]:
pip install ucimlrepo

In [3]:
from ucimlrepo import fetch_ucirepo

In [4]:
# fetch dataset
breast_cancer_wisconsin_diagnostic = fetch_ucirepo(id=17)
# data (as pandas dataframes)
X = breast_cancer_wisconsin_diagnostic.data.features
y = breast_cancer_wisconsin_diagnostic.data.targets
# metadata
print(breast_cancer_wisconsin_diagnostic.metadata)
# variable information
print(breast_cancer_wisconsin_diagnostic.variables)


{'uci_id': 17, 'name': 'Breast Cancer Wisconsin (Diagnostic)', 'repository_url': 'https://archive.ics.uci.edu/dataset/17/breast+cancer+wisconsin+diagnostic', 'data_url': 'https://archive.ics.uci.edu/static/public/17/data.csv', 'abstract': 'Diagnostic Wisconsin Breast Cancer Database.', 'area': 'Health and Medicine', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 569, 'num_features': 30, 'feature_types': ['Real'], 'demographics': [], 'target_col': ['Diagnosis'], 'index_col': ['ID'], 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 1993, 'last_updated': 'Fri Nov 03 2023', 'dataset_doi': '10.24432/C5DW2B', 'creators': ['William Wolberg', 'Olvi Mangasarian', 'Nick Street', 'W. Street'], 'intro_paper': {'title': 'Nuclear feature extraction for breast tumor diagnosis', 'authors': 'W. Street, W. Wolberg, O. Mangasarian', 'published_in': 'Electronic imaging', 'year': 1993, 'url': 'https://www.semanticscholar.org/paper/53

In [7]:
data = pd.read_csv('wdbc.data')


In [8]:
data.head()


842302  M  17.99  10.38   122.8    1001   0.1184   0.2776  0.3001  \
0    842517  M  20.57  17.77  132.90  1326.0  0.08474  0.07864  0.0869   
1  84300903  M  19.69  21.25  130.00  1203.0  0.10960  0.15990  0.1974   
2  84348301  M  11.42  20.38   77.58   386.1  0.14250  0.28390  0.2414   
3  84358402  M  20.29  14.34  135.10  1297.0  0.10030  0.13280  0.1980   
4    843786  M  12.45  15.70   82.57   477.1  0.12780  0.17000  0.1578   

    0.1471  ...  25.38  17.33   184.6    2019  0.1622  0.6656  0.7119  0.2654  \
0  0.07017  ...  24.99  23.41  158.80  1956.0  0.1238  0.1866  0.2416  0.1860   
1  0.12790  ...  23.57  25.53  152.50  1709.0  0.1444  0.4245  0.4504  0.2430   
2  0.10520  ...  14.91  26.50   98.87   567.7  0.2098  0.8663  0.6869  0.2575   
3  0.10430  ...  22.54  16.67  152.20  1575.0  0.1374  0.2050  0.4000  0.1625   
4  0.08089  ...  15.47  23.75  103.40   741.6  0.1791  0.5249  0.5355  0.1741   

   0.4601   0.1189  
0  0.2750  0.08902  
1  0.3613  0.08758  
2  0.6638  0.17300  
3  0.2364  0.07678  
4  0.3985  0.12440  

[5 rows x 32 columns]

In [10]:
data.columns = ['ID', 'Diagnosis', 'Mean Radius', 'Mean Texture', 'Mean Perimeter', 'Mean Area', 'Mean Smoothness', 'Mean Compactness', 'Mean Concavity', 'Mean Concave Points', 'Mean Symmetry', 'Mean Fractal Dimension', 'SE Radius', 'SE Texture', 'SE Perimeter', 'SE Area', 'SE Smoothness', 'SE Compactness', 'SE Concavity', 'SE Concave Points', 'SE Symmetry', 'SE Fractal Dimension', 'Worst Radius', 'Worst Texture', 'Worst Perimeter', 'Worst Area', 'Worst Smoothness', 'Worst Compactness', 'Worst Concavity', 'Worst Concave Points', 'Worst Symmetry', 'Worst Fractal Dimension']
data['Diagnosis'] = data['Diagnosis'].map({'M': 1, 'B': 0})


In [12]:
data.head()

ID  Diagnosis  Mean Radius  Mean Texture  Mean Perimeter  Mean Area  \
0    842517          1        20.57         17.77          132.90     1326.0   
1  84300903          1        19.69         21.25          130.00     1203.0   
2  84348301          1        11.42         20.38           77.58      386.1   
3  84358402          1        20.29         14.34          135.10     1297.0   
4    843786          1        12.45         15.70           82.57      477.1   

   Mean Smoothness  Mean Compactness  Mean Concavity  Mean Concave Points  \
0          0.08474           0.07864          0.0869              0.07017   
1          0.10960           0.15990          0.1974              0.12790   
2          0.14250           0.28390          0.2414              0.10520   
3          0.10030           0.13280          0.1980              0.10430   
4          0.12780           0.17000          0.1578              0.08089   

   ...  Worst Radius  Worst Texture  Worst Perimeter  Worst Area  \
0  ...         24.99          23.41           158.80      1956.0   
1  ...         23.57          25.53           152.50      1709.0   
2  ...         14.91          26.50            98.87       567.7   
3  ...         22.54          16.67           152.20      1575.0   
4  ...         15.47          23.75           103.40       741.6   

   Worst Smoothness  Worst Compactness  Worst Concavity  Worst Concave Points  \
0            0.1238             0.1866           0.2416                0.1860   
1            0.1444             0.4245           0.4504                0.2430   
2            0.2098             0.8663           0.6869                0.2575   
3            0.1374             0.2050           0.4000                0.1625   
4            0.1791             0.5249           0.5355                0.1741   

   Worst Symmetry  Worst Fractal Dimension  
0          0.2750                  0.08902  
1          0.3613                  0.08758  
2          0.6638                  0.17300  
3          0.2364                  0.07678  
4          0.3985                  0.12440  

[5 rows x 32 columns]

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 568 entries, 0 to 567
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   ID                       568 non-null    int64  
 1   Diagnosis                568 non-null    int64  
 2   Mean Radius              568 non-null    float64
 3   Mean Texture             568 non-null    float64
 4   Mean Perimeter           568 non-null    float64
 5   Mean Area                568 non-null    float64
 6   Mean Smoothness          568 non-null    float64
 7   Mean Compactness         568 non-null    float64
 8   Mean Concavity           568 non-null    float64
 9   Mean Concave Points      568 non-null    float64
 10  Mean Symmetry            568 non-null    float64
 11  Mean Fractal Dimension   568 non-null    float64
 12  SE Radius                568 non-null    float64
 13  SE Texture               568 non-null    float64
 14  SE Perimeter             5

In [14]:
X = data.drop(['ID','Diagnosis'],axis=1)
Y = data['Diagnosis']

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2, random_state=0)


In [16]:
X_train.shape, X_test.shape, Y_train.shape, Y_test.shape

((454, 30), (114, 30), (454,), (114,))

In [17]:
model= Sequential()

In [18]:
model.add(Dense(16,input_dim=30,activation='relu'))

In [19]:
model.add(Dense(8,activation='relu'))

In [21]:
model.add(Dense(1,activation='sigmoid'))

In [23]:
y_pred = model.predict(X_test)


4/4 [==============================] - 0s 3ms/step


In [24]:
y_pred_binary=(y_pred> 0.5).astype(int)

In [25]:
# Print the binary predictions
print(y_pred_binary)

[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]


In [26]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X_train, Y_train, epochs=100, batch_size=10)

Epoch 1/100
46/46 [==============================] - 1s 2ms/step - loss: 4.5301 - accuracy: 0.3370
Epoch 2/100
46/46 [==============================] - 0s 2ms/step - loss: 0.6960 - accuracy: 0.6300
Epoch 3/100
46/46 [==============================] - 0s 2ms/step - loss: 0.6876 - accuracy: 0.6300
Epoch 4/100
46/46 [==============================] - 0s 2ms/step - loss: 0.6847 - accuracy: 0.6300
Epoch 5/100
46/46 [==============================] - 0s 2ms/step - loss: 0.6818 - accuracy: 0.6300
Epoch 6/100
46/46 [==============================] - 0s 2ms/step - loss: 0.6792 - accuracy: 0.6300
Epoch 7/100
46/46 [==============================] - 0s 2ms/step - loss: 0.6770 - accuracy: 0.6300
Epoch 8/100
46/46 [==============================] - 0s 2ms/step - loss: 0.6750 - accuracy: 0.6300
Epoch 9/100
46/46 [==============================] - 0s 2ms/step - loss: 0.6732 - accuracy: 0.6300
Epoch 10/100
46/46 [==============================] - 0s 2ms/step - loss: 0.6716 - accuracy: 0.6300
Epoch 11/

In [27]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter=5000)

In [28]:
model.fit(X_train,Y_train)


LogisticRegression(max_iter=5000)

In [29]:
y_pred = model.predict(X_test)

In [30]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(classification_report(Y_test, y_pred))

              precision    recall  f1-score   support

           0       0.93      0.99      0.96        71
           1       0.97      0.88      0.93        43

    accuracy                           0.95       114
   macro avg       0.95      0.93      0.94       114
weighted avg       0.95      0.95      0.95       114



In [31]:
confusion_matrix(Y_test,y_pred)


array([[70,  1],
       [ 5, 38]])

In [32]:
accuracy_score(Y_test, y_pred)

0.9473684210526315

In [33]:
#SVM
from sklearn.svm import SVC
svm = SVC()


In [34]:
svm.fit(X_train,Y_train)

SVC()

In [35]:
y_preds = svm.predict(X_test)

In [36]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(classification_report(Y_test, y_preds))

              precision    recall  f1-score   support

           0       0.87      1.00      0.93        71
           1       1.00      0.74      0.85        43

    accuracy                           0.90       114
   macro avg       0.93      0.87      0.89       114
weighted avg       0.92      0.90      0.90       114



In [37]:
confusion_matrix(Y_test,y_preds)

array([[71,  0],
       [11, 32]])

In [38]:
accuracy_score(Y_test,y_preds)

0.9035087719298246